import { JobPosting, StudentApplication, DriveEvent, PlacementOffer, SkillGapItem, ReadinessCategory } from '@/types/placement';
import { NotificationItem } from '@/types/auth';

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    title: 'Drive Scheduled: TCS Digital 2026',
    message: 'Online Assessment scheduled for 10th Oct, 10:00 AM in Central Lab 1 & 2.',
    timestamp: '10 mins ago',
    read: false,
    type: 'info',
    link: '/student/schedule',
  },
  {
    id: 'notif_2',
    title: 'Eligibility Verified: Deloitte USI',
    message: 'Academic credentials verified for Associate Analyst profile (CGPA threshold 7.5 met).',
    timestamp: '2 hours ago',
    read: false,
    type: 'success',
    link: '/student/applications',
  },
  {
    id: 'notif_3',
    title: 'Resume Indexing Complete',
    message: 'AI parsed resume v3.2. Technical readiness benchmark updated to 82/100.',
    timestamp: 'Yesterday',
    read: true,
    type: 'info',
    link: '/student/readiness',
  },
  {
    id: 'notif_4',
    title: 'BPUT Placement Cell Notice',
    message: 'Mandatory mock technical round registration ends tomorrow 5:00 PM.',
    timestamp: '2 days ago',
    read: true,
    type: 'warning',
    link: '/officer/support',
  },
];

export const DEMO_JOBS: JobPosting[] = [
  {
    id: 'job_101',
    title: 'Digital Software Engineer (Full Stack)',
    company: 'Tata Consultancy Services',
    location: 'Bhubaneswar / Hyderabad / Pune',
    type: 'Full-time',
    packageCTC: '₹9.00 - 11.50 LPA',
    minCGPA: 7.5,
    branches: ['CSE', 'IT', 'ECE', 'EE'],
    batch: '2026 Graduating',
    status: 'Active',
    deadline: '2026-10-14',
    rolesDescription: 'Responsible for modern enterprise microservices, cloud deployments, and resilient backend architectures.',
    applicantsCount: 342,
    shortlistedCount: 88,
    offersCount: 16,
    rounds: ['Online Coding Test', 'Technical Interview 1', 'Managerial Round', 'HR & Verification'],
  },
  {
    id: 'job_102',
    title: 'Associate Cloud Consultant',
    company: 'Deloitte USI',
    location: 'Bengaluru / Hyderabad',
    type: 'Full-time',
    packageCTC: '₹8.60 LPA',
    minCGPA: 7.0,
    branches: ['CSE', 'IT', 'ECE'],
    batch: '2026 Graduating',
    status: 'Active',
    deadline: '2026-10-18',
    rolesDescription: 'Design, develop, and automate enterprise migration to cloud environments with infrastructure-as-code.',
    applicantsCount: 290,
    shortlistedCount: 64,
    offersCount: 0,
    rounds: ['Aptitude + Tech MCQ', 'Case Study Round', 'Partner Interview'],
  },
  {
    id: 'job_103',
    title: 'Systems Development Engineer I',
    company: 'Amazon Development Centre',
    location: 'Hyderabad / Chennai',
    type: 'Full-time',
    packageCTC: '₹18.00 - 24.50 LPA',
    minCGPA: 8.0,
    branches: ['CSE', 'IT'],
    batch: '2026 Graduating',
    status: 'Active',
    deadline: '2026-10-22',
    rolesDescription: 'Build high-scale distributed systems and core platform microservices for high throughput.',
    applicantsCount: 412,
    shortlistedCount: 42,
    offersCount: 5,
    rounds: ['Online Assessment', 'Tech Screen', '3x Onsite Distributed Coding', 'Bar Raiser'],
  },
  {
    id: 'job_104',
    title: 'Embedded Systems Engineer',
    company: 'L&T Technology Services',
    location: 'Mysuru / Bengaluru',
    type: 'Full-time',
    packageCTC: '₹6.50 - 8.00 LPA',
    minCGPA: 6.8,
    branches: ['ECE', 'EEE', 'Mechanical'],
    batch: '2026 Graduating',
    status: 'Upcoming',
    deadline: '2026-10-28',
    rolesDescription: 'Automotive and IoT firmware development, real-time operating systems (RTOS), and hardware debugging.',
    applicantsCount: 185,
    shortlistedCount: 0,
    offersCount: 0,
    rounds: ['Core Domain Test', 'Lab Practical Round', 'HR Discussion'],
  },
];

export const DEMO_STUDENT_APPLICATIONS: StudentApplication[] = [
  {
    id: 'app_1',
    jobId: 'job_101',
    jobTitle: 'Digital Software Engineer (Full Stack)',
    company: 'Tata Consultancy Services',
    appliedDate: '2026-09-28',
    stage: 'Technical Round',
    statusBadge: 'info',
    nextActionDate: '2026-10-12 11:30 AM',
    nextActionTitle: 'Technical Interview (Panel B - Virtual)',
    eligibilityMet: true,
  },
  {
    id: 'app_2',
    jobId: 'job_102',
    jobTitle: 'Associate Cloud Consultant',
    company: 'Deloitte USI',
    appliedDate: '2026-10-01',
    stage: 'Shortlisted',
    statusBadge: 'success',
    nextActionDate: '2026-10-15 02:00 PM',
    nextActionTitle: 'Online Aptitude & Code Evaluation',
    eligibilityMet: true,
  },
  {
    id: 'app_3',
    jobId: 'job_103',
    jobTitle: 'Systems Development Engineer I',
    company: 'Amazon Development Centre',
    appliedDate: '2026-09-24',
    stage: 'Assessment',
    statusBadge: 'warning',
    nextActionDate: '2026-10-10 09:00 AM',
    nextActionTitle: 'Hackerrank Proctored Screening',
    eligibilityMet: true,
  },
];

export const DEMO_DRIVE_EVENTS: DriveEvent[] = [
  {
    id: 'evt_1',
    title: 'TCS Digital Technical Interviews (Slot 1)',
    company: 'Tata Consultancy Services',
    eventType: 'Technical Interview',
    date: '2026-10-12',
    timeSlot: '10:00 AM - 01:00 PM',
    venueOrLink: 'Placement Block Room 302 & Virtual Panel A',
    targetRole: 'Digital Software Engineer',
    conflictsDetected: 0,
    status: 'Scheduled',
  },
  {
    id: 'evt_2',
    title: 'Deloitte USI Online Assessment Drive',
    company: 'Deloitte USI',
    eventType: 'Online Assessment',
    date: '2026-10-15',
    timeSlot: '02:00 PM - 04:30 PM',
    venueOrLink: 'Central Computing Lab 1, 2, 3 (300 Seats)',
    targetRole: 'Associate Cloud Consultant',
    conflictsDetected: 0,
    status: 'Scheduled',
  },
  {
    id: 'evt_3',
    title: 'Amazon Systems Assessment Screening',
    company: 'Amazon Development Centre',
    eventType: 'Online Assessment',
    date: '2026-10-10',
    timeSlot: '09:00 AM - 11:30 AM',
    venueOrLink: 'Proctored Remote Online Link (Check Email)',
    targetRole: 'SDE-I',
    conflictsDetected: 1,
    status: 'Scheduled',
  },
];

export const DEMO_OFFERS: PlacementOffer[] = [
  {
    id: 'off_901',
    company: 'Tata Consultancy Services',
    role: 'Digital Software Engineer',
    ctc: '₹9.20 LPA',
    baseSalary: '₹7.50 LPA + Incentives',
    joiningLocation: 'Bhubaneswar Infocity / Pune',
    offerDate: '2026-10-02',
    acceptanceDeadline: '2026-10-20',
    status: 'Pending Review',
    documentRef: 'BPUT-TCS-OFFER-2026-8821.pdf',
  },
];

export const DEMO_SKILL_GAPS: SkillGapItem[] = [
  {
    skill: 'Data Structures & Algorithms',
    category: 'Core Computer Science',
    currentLevel: 'Proficient',
    requiredLevel: 'Proficient',
    status: 'Met',
    targetRoleRelevance: 'High priority for Amazon SDE and TCS Digital',
  },
  {
    skill: 'System Design & High Concurrency',
    category: 'System Design',
    currentLevel: 'Intermediate',
    requiredLevel: 'Expert',
    status: 'Gap Detected',
    targetRoleRelevance: 'Crucial for product tier (Amazon, Cisco, Oracle)',
  },
  {
    skill: 'Cloud Deployment (Docker/AWS)',
    category: 'Modern Frameworks',
    currentLevel: 'Novice',
    requiredLevel: 'Intermediate',
    status: 'Priority Focus',
    targetRoleRelevance: 'Recommended for Deloitte Cloud Consultant role',
  },
  {
    skill: 'Technical Communication & Behavioral Scenarios',
    category: 'Soft Skills',
    currentLevel: 'Intermediate',
    requiredLevel: 'Proficient',
    status: 'Met',
    targetRoleRelevance: 'Direct impact on Managerial & Bar Raiser rounds',
  },
];

export const DEMO_READINESS_METRICS: ReadinessCategory[] = [
  {
    title: 'Technical Problem Solving',
    score: 84,
    benchmark: 75,
    summary: 'Strong grasp of Graph theory, Dynamic Programming, and SQL query optimization.',
    status: 'Strong',
  },
  {
    title: 'System Architecture & OS',
    score: 68,
    benchmark: 75,
    summary: 'Review Memory management, distributed caching, and microservices patterns.',
    status: 'Needs Attention',
  },
  {
    title: 'Domain Project Defense',
    score: 88,
    benchmark: 80,
    summary: 'Deep clarity on final year capstone architecture and engineering trade-offs.',
    status: 'Strong',
  },
  {
    title: 'HR & Behavioral Alignment',
    score: 82,
    benchmark: 78,
    summary: 'STAR method answers structured well for leadership scenarios.',
    status: 'Good',
  },
];

export const DEMO_OFFICER_STUDENTS = [
  {
    id: 's1',
    regNo: '2201106284',
    name: 'Aarav Mohapatra',
    branch: 'CSE',
    cgpa: 8.82,
    backlogs: 0,
    placementStatus: 'Shortlisted (2)',
    readinessScore: 84,
    batch: '2026',
    verified: true,
  },
  {
    id: 's2',
    regNo: '2201106190',
    name: 'Priyanka Das',
    branch: 'IT',
    cgpa: 9.15,
    backlogs: 0,
    placementStatus: 'Offered (1)',
    readinessScore: 92,
    batch: '2026',
    verified: true,
  },
  {
    id: 's3',
    regNo: '2201106312',
    name: 'Rohan Tripathy',
    branch: 'ECE',
    cgpa: 7.94,
    backlogs: 0,
    placementStatus: 'Eligible',
    readinessScore: 76,
    batch: '2026',
    verified: true,
  },
  {
    id: 's4',
    regNo: '2201106405',
    name: 'Sneha Nayak',
    branch: 'CSE',
    cgpa: 8.45,
    backlogs: 0,
    placementStatus: 'Assessment Ready',
    readinessScore: 81,
    batch: '2026',
    verified: true,
  },
  {
    id: 's5',
    regNo: '2201106088',
    name: 'Debashis Panda',
    branch: 'EE',
    cgpa: 7.21,
    backlogs: 0,
    placementStatus: 'Verification Pending',
    readinessScore: 65,
    batch: '2026',
    verified: false,
  },
];
